storeType: ONHEAP
threadCount: 33
entryCount: 20000000
offHeapSize: "0"
maxOnHeapCount: 20000000
batchCount: 50000
maxValueSize: 1000
minValueSize: 200
hotSetPercentage: 99
rounds: 4
updatePercentage: 10
diskStorePath: java.io.tmpdir
monitoringEnabled: false
useTerracottaArray: false
TerracottaArrayURL: localhost:9510
Consistency: eventual
Concurrency: 0
nonStopCache: false
nonStopTimeoutMillis: 30000
nonStopTimeoutBehavior: localreads
ehcacheFileEnabled: false
ehcacheFileURL: ehcache.xml
ehcacheFileCacheName: myTestCache